# Generated by Django 5.1.7 on 2025-05-06 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ОКУ', 'Окулист'), ('ДЕР', 'Дерматолог'), ('НЕВ', 'Невролог'), ('ТЕР', 'Терапевт')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ОКУ', 'Окулист'), ('ДЕР', 'Дерматолог'), ('НЕВ', 'Невролог'), ('ТЕР', 'Терапевт')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
    ]
