# Generated by Django 5.1.7 on 2025-05-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ОКУ', 'Окулист'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог'), ('НЕВ', 'Невролог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ОКУ', 'Окулист'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог'), ('НЕВ', 'Невролог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
    ]
