# Generated by Django 5.1.7 on 2025-05-14 13:21

import entities.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_alter_doctor_gender_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('НЕВ', 'Невролог'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог'), ('ОКУ', 'Окулист')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('НЕВ', 'Невролог'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог'), ('ОКУ', 'Окулист')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='diagnosis',
            field=models.TextField(blank=True, validators=[entities.validators.validate_russian_text], verbose_name='Диагнозы'),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='examination',
            field=models.TextField(validators=[entities.validators.validate_russian_text], verbose_name='Физический осмотр'),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='prescriptions',
            field=models.TextField(validators=[entities.validators.validate_russian_text], verbose_name='Рецепт'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Ж', 'Женский'), ('М', 'Мужской')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='diagnosis',
            field=models.TextField(blank=True, validators=[entities.validators.validate_russian_text], verbose_name='Диагнозы'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='examination',
            field=models.TextField(validators=[entities.validators.validate_russian_text], verbose_name='Физический осмотр'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='prescriptions',
            field=models.TextField(validators=[entities.validators.validate_russian_text], verbose_name='Рецепт'),
        ),
    ]
