# Generated by Django 5.1.7 on 2025-05-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_alter_doctor_gender_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalvisit',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код МКБ-10'),
        ),
        migrations.AddField(
            model_name='visit',
            name='icd10_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Код МКБ-10'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ОКУ', 'Окулист'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог'), ('ХИР', 'Хирург'), ('НЕВ', 'Невролог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ОКУ', 'Окулист'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог'), ('ХИР', 'Хирург'), ('НЕВ', 'Невролог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
    ]
