# Generated by Django 5.1.7 on 2025-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_alter_doctor_gender_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalvisit',
            name='icd10_code',
        ),
        migrations.RemoveField(
            model_name='visit',
            name='icd10_code',
        ),
        migrations.AddField(
            model_name='historicalvisit',
            name='icd10_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='visit',
            name='icd10_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ДЕР', 'Дерматолог'), ('ОКУ', 'Окулист'), ('ТЕР', 'Терапевт'), ('НЕВ', 'Невролог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ДЕР', 'Дерматолог'), ('ОКУ', 'Окулист'), ('ТЕР', 'Терапевт'), ('НЕВ', 'Невролог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicalpatient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], default='М', max_length=1, verbose_name='Пол'),
        ),
    ]
