# Generated by Django 5.1.7 on 2025-05-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_alter_doctor_gender_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ОКУ', 'Окулист'), ('НЕВ', 'Невролог'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ХИР', 'Хирург'), ('ОКУ', 'Окулист'), ('НЕВ', 'Невролог'), ('ТЕР', 'Терапевт'), ('ДЕР', 'Дерматолог')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='icd10_diagnosis',
            field=models.JSONField(blank=True, null=True, verbose_name='Диагноз по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='icd10_diagnosis',
            field=models.JSONField(blank=True, null=True, verbose_name='Диагноз по МКБ-10'),
        ),
    ]
