# Generated by Django 5.1.7 on 2025-05-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ТЕР', 'Терапевт'), ('ХИР', 'Хирург'), ('НЕВ', 'Невролог'), ('ДЕР', 'Дерматолог'), ('ОКУ', 'Окулист')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ТЕР', 'Терапевт'), ('ХИР', 'Хирург'), ('НЕВ', 'Невролог'), ('ДЕР', 'Дерматолог'), ('ОКУ', 'Окулист')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicalvisit',
            name='icd10_diagnosis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Диагноз по МКБ-10'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='icd10_diagnosis',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Диагноз по МКБ-10'),
        ),
    ]
