# Generated by Django 5.1.7 on 2025-05-16 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_alter_doctor_specialty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('ДЕР', 'Дерматолог'), ('ТЕР', 'Терапевт'), ('ХИР', 'Хирург'), ('НЕВ', 'Невролог'), ('ОКУ', 'Окулист')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
        migrations.AlterField(
            model_name='historicaldoctor',
            name='specialty',
            field=models.CharField(choices=[('ДЕР', 'Дерматолог'), ('ТЕР', 'Терапевт'), ('ХИР', 'Хирург'), ('НЕВ', 'Невролог'), ('ОКУ', 'Окулист')], default='TER', max_length=3, verbose_name='Специальность'),
        ),
    ]
